- CHANGES
- src/gpgpu-sim/mem_fetch.h
- src/gpgpu-sim/shader.cc
Making sure we immediately fetch after a MISS comes back from cache. This prevents counting a hit the next time we try to fetch the same instruction.
> Fixing icache bug where for each miss we also count a hit.

- CHANGES
- src/intersim2/interconnect_interface.cpp
Fixed bug #88. Initial ejection buffer and boundary buffer with the interconnection node number
See bug at:
http://www.gpgpu-sim.org/bugs/show_bug.cgi?id=88
> Fixed bug #88. Initial ejection buffer and boundary buffer with the interconnection node number

- CHANGES
- cuobjdump_to_ptxplus/Makefile
- libcuda/Makefile
- src/intersim2/Makefile
Having lex and yacc generate to the source directory causes issues when trying to build multiple configs at the same time from the same source. Now the files go into the ./build/ directory - just like everything else that gets generated in the build process. It also make the cleanup process much easier because all you have to do is delete the ./build directory and everything is clean
> Getting rid of all the intermediate files that get generated into the source directory

- CHANGES
- Makefile
- libcuda/cuda_runtime_api.cc
- libcuda/cuobjdump.l
- libcuda/cuobjdump.y
- libopencl/opencl_runtime_api.cc
- setup_environment
- src/cuda-sim/ptx_loader.cc
- src/cuda-sim/ptx_loader.h
This an initial support for CUDA 7.5. It puts it at the same level of current GPGPUSim-dev support for 5.0, 5.5 and 6.0. This support is limited to ability to parse the headers correctly, thus, if the benchmark has PTX/SASS instuctions that is not yet supported it would fail.
Also, changes have been made to allow for configurable SM version.
Regression for 4.2 on GTX480 has run successful. For non-fully supported verions (>=5.5 and <=7.5), it was tested on simple sdk benchmarks. 
Attached are files that shows the cuobjdump output for different versions.
[template_75.txt](https://github.com/gpgpu-sim/gpgpu-sim_distribution/files/265056/template_75.txt)
[template_55.txt](https://github.com/gpgpu-sim/gpgpu-sim_distribution/files/265054/template_55.txt) …
> Initial support for 7.5 - tested on simple sdk benchmaks (e.g., template, vectorAdd, ...)

- src/cuda-sim/ptx_ir.cc
The block containing predicate ret instruction should add the consecutive block to its successor_ids set. next_addr should be assigned with current instruction address adding instruction size instead of 1. Block connections can be print out to test whether block are correctly linked.
Signed-off-by: Mengchi Zhang <zhan2308@purdue.edu>
> Fix next block addr to link predicate ret block to consecutive block

- Makefile
- src/cuda-sim/Makefile
- src/cuda-sim/cuda-sim.cc
- version
- version_detection.mk
This has a bunch of potential uses, but it makes running simulations much easier because we can just print the exact git commit that this run of GPGPU-Sim was built for.
The primary motivator is to make it very clear when running simulations which version of GPGPU-Sim you ran.
Tested on CUDA 4.2 and hi-jacking the SONAME in the built exec does not seem to have a detrimental effect.
> Embedding the gpgpu-sim version information (the commit number that was built) in the shared object executable.

- src/gpgpu-sim/gpu-sim.h
Bug found and fixed by mahmoud - we were not using all the banks in the DRAM.
Pre-regressed by the purdue system.
> Fixing BankGroup Indexing Bug

- src/intersim2/Makefile
Without this, incremental builds that change files that the interconnect is using in GPGPU-Sim will not trigger interconnect rebuilds - which leads to weird runtime problems because the interconnect was built with old headers.
> Updating the interconnect simulator to properly check for dependencies

- Makefile
- linux-so-version.txt
There does not seem to be a hard requirement on what the number is, only that it is there.
> Apps compiled with newer versions of CUDA want the version number embedded in the so

- src/cuda-sim/cuda-math.h
Without this Redhat 6 default gcc will not compile.
> Getting the simulator to compile with older versions of g++

- cuobjdump_to_ptxplus/cuobjdumpInst.cc
- libcuda/cuda_runtime_api.cc
- src/cuda-sim/cuda-math.h
- src/cuda-sim/cuda-sim.cc
- src/cuda-sim/ptx_ir.h
- src/debug.cc
- src/debug.h
- src/gpgpu-sim/dram.h
- src/gpgpu-sim/mem_fetch.cc
- src/gpgpu-sim/mem_fetch.h
- src/gpgpu-sim/shader.h
- src/stream_manager.h
This fixes some errors and warnings reported by clang during compilation. Most of them are cleanups of class vs struct. I took clang's advice of if they should be a class or a struct (and it compiles with fewer warnings). There are a few other miscellaneous changes here, too.
> Cleanup clang warnings

- libcuda/cuobjdump.l
This comment made the build fail in ubuntu 18.04 due to a flex error. This error is probably produced by a flex bug.
> libcuda: removed comment from cuobjdump.l

- src/cuda-sim/ptx.l
- src/cuda-sim/ptx.y
- src/cuda-sim/ptx_parser.cc
Hello
I was trying to simulate an OpenCL kernel with your simulator but ran into some weird parse errors of valid OpenCL code:
- Long lines were truncated, so I increased the buffer size. I don't know if this has any real effect on the parsing or just affects the debugging lines.
- Arrays in the constant memory space (such as `constant float arr[10]`) are translated in the PTX as `.visible .const .align 4 .b8 arr[40]`. However, the PTX grammar doesn't seem to like that `.visible` specificator. I added a rule to allow that specificator in the `var_spec` rule, I don't know if further modifications should be done.
- When passing arguments to the kernel in the constant memory space, (such as `mykernel(constant float* arg)`) the grammar chokes on the _const_ specificator. I changed it to allow …
> Naive fix of OpenCL parse errors

- libcuda/cuda_runtime_api.cc
Update cudaStreamDestroy's functionality to synchronize before destroying streams.
> Update cudaStreamDestroy function

- src/cuda-sim/ptx.l
Added instruction "bar.warp.sync". This instruction is parsed as NOP which is ok for stack-based reconvergence. This instruction is used in cuDNN with Cuda-9.0
> Instruction added to enable support for cuDNN with cuda-9.0

- configs/tested-cfgs/SM7_TITANV/gpgpusim.config
- src/gpgpu-sim/gpu-sim.cc
- src/gpgpu-sim/shader.cc
- src/gpgpu-sim/shader.h
Change spelling of "-adpative_volta_cache_config" parameter and subsequent uses to "-adaptive_volta_cache_config".
> Fix spelling from adpative -> adaptive for volta cache config

- aerialvision/organizedata.py
I've found and fixed a minor bug when I running AerialVision.
```
Traceback (most recent call last):
File "./aerialvision.py", line 79, in <module>
import startup
File "/home/redcarrottt/gpgpu-sim_distribution/aerialvision/startup.py", line 68, in <module>
import guiclasses
File "/home/redcarrottt/gpgpu-sim_distribution/aerialvision/guiclasses.py", line 81, in <module>
import organizedata
File "/home/redcarrottt/gpgpu-sim_distribution/aerialvision/organizedata.py", line 100
data_type_char = {int:'I', float:'f'}
^
IndentationError: unexpected indent
```
> Fix indentation bug of AerialVision

- src/cuda-sim/ptx.y
Changes have been made to the parser in order to recognize function pointers and ignore them for now. This is required for pytorch to run on gpgpu-sim.
> added temp. solution to bypass function pointers

- libopencl/opencl_runtime_api.cc
This pull request contain some of the clean fixes I performed to make OpenCL simulation work again in the current dev branch.
In addition to this, I worked around Issue #138 by simply defining no_of_ptx in opencl_runtime_api.cc . I didn't include this change in the pull request as I am unable to oversee the consequences of such a change.
Other changes not included but crucial for running OpenCL benchmarks again appear to be non-portable:
-  ptx_loader.cc contains some sed commands to change the version number in the PTX intermediate. Both the search and the replace version number had to be changed to work with the toolchain on my PC.
- Changed the default sm_version in gpgpu_ptxinfo_load_from_string() from 20 to 35, to match the GPU in my PC.
Similar non-portable changes might be required …
> Assortment of OpenCL fixes

- configs/tested-cfgs/SM2_GTX480/gpgpusim.config
- configs/tested-cfgs/SM6_TITANX/gpgpusim.config
- configs/tested-cfgs/SM7_TITANV/gpgpusim.config
- src/cuda-sim/cuda-sim.cc
- src/gpgpu-sim/shader.cc
shfl latency is hardcoded to 32, but int_unit pipeline depth is set to int_latency[1](==max op latency), so sigsegv occurs. so shfl latency is added to config and option parser
> take account of shfl latency

- libcuda/cuda_runtime_api.cc
- src/stream_manager.cc
- src/stream_manager.h
fix the problem mentioned at pr https://github.com/gpgpu-sim/gpgpu-sim_distribution/pull/135.
1. returning false when an event for stream_wait_event has not done
2. fix stream selection algorithm: a stream next to the last selected stream is selected now. This prevents only the first stream consume all the oppotunity
3. fix cudaStreamWaitEvent impl --> stream wait event now does not wait the event that has never issued
> Deadlock fix from stream_manager

- aerialvision/guiclasses.py
Exception `AttributeError: 'AxesImage' object has no attribute 'get_axes'` occurs when creating/refreshing a parallel intensity plot. Updated the get_axes().get_position() matplotlib call to get_window_extent().
> fixed exception for parallel intensity plots in AerialVision
